### ISSUE TITLE
Speaker

### ISSUE THREAD

**Issue by sergio9104** [MedellinCSS/meetup#1]
# Ahora, ¿Qué te gustaría?...

* [x] 🍄 Ser el próximo speaker
* [ ] 🌸 Dar feedback
* [ ] 🌻 Dar una idea
* [ ] 🚀 Otro

## Descripción
Enseñar las capacidades que posee CSS3 para la creación de animaciones, en esta charla enseñaria
• Transformaciones de 2 dimensiones
• Ejemplos de transición simples y avanzados 
• Animaciones con keyframes
• Animaciones en 3D

**Comment by teffcode** [comment]
Excelente @sergio9104 💚 Curiosamente, las animaciones son de mis temas favoritos 😍 

Graciasss por querer ser parte de nuestro grupo de speakers 🎤🎨

Te gustaría dar esta charla el *30 de agosto* ?

**Comment by sergio9104** [comment]
Si, para mi el 30 de agosto esta bien.
