### ISSUE TITLE
Community project idea

### ISSUE THREAD

**Issue by D4v1d98Ru1z** [MedellinCSS/meetup#11]
# Ahora, ¿Qué te gustaría?...

* [ ] 🍄 Ser el próximo speaker
* [ ] 🌸 Dar feedback
* [x] 🌻 Dar una idea
* [ ] 🚀 Otro

## Descripción

Durante mi proceso de aprendizaje en css, he encontrado una serie de recursos para practicar mis skills tales como [CSS grid garden](https://cssgridgarden.com) entre otras. Por lo cual me gustaría que se desarrollara en comunidad un proyecto similar en el que se colecten conceptos basicos, avanzados e incluso lo más nuevo y que miembros tanto de la comunidad como a nivel global pudiesen usar esta herramienta para practicar sus habilidades.

La idea surgió gracias a un scketch que estaba realizando @teffcode y fue publicado en un Instagram stories. Quisiera saber que opina la comunidad sobre esta idea? :blush:

**Comment by teffcode** [comment]
Hola @D4v1d98Ru1z ! 

Mil gracias por tu aporte a la comunidad 😊Me gusta mucho tu idea !

Sin embargo, me gustaría saber algunas cosas:
1. En vista de que hay tantos temas en CSS, ¿ cuál crees que es esencial para comenzar este proyecto ? 
2. ¿ Qué herramientas consideras importantes para la realización del proyecto ?
3. ¿ Cuántas personas deberían estar en el proyecto ? ¿ Te gustaría estar en el equipo ?
4. ¿ Cuánto tiempo tomaría la realización del mismo ?
5. ¿ Te gustaría que fuera un proyecto hecho por los mismos miembros de la comunidad ? Si sí, ¿ cómo te imaginas la realización del mismo ?

Estas preguntas son con el fin de elaborar un poco más la idea y así poder materializarla. Si tienes dudas al respecto o quieres que te ayudemos, solo dinos. Estamos para trabajar en equipo !

Que tengas feliz día !

**Comment by D4v1d98Ru1z** [comment]
Muchas gracias, me alegra que te haya gustado :smiley: 

Acá tengo algunas respuestas, aunque me gustaría también que la comunidad que tiene más conocimiento me pudiese aconsejar.

1. Tengo pensado manejar temas básicos pero fundamentales, como FlexBox, CSS grid, incluso no se si también algo de responsive. ¿A la comunidad que temas les gustaría trabajar?
3. Quisiera que se trabajará el proyecto totalmente open source con el fin de que cualquier persona que quiera contribuir sea bienvenida. Para definir el equipo considero que sea pertinente saber quienes estarían interesados. Y la verdad sí me gustaría ser parte del equipo :smile: 
5. Todos los que quieran participar en el proyecto pueden ser bienvenidos, ya sean tanto miembros como no miembros de la comunidad.

Las preguntas faltantes y que quedaron incompletas si me gustaría que me apoyaran un poco más en eso.

Ten un lindo día igualmente, gracias.

**Comment by teffcode** [comment]
Hola @D4v1d98Ru1z  !

Tendremos nuestro próximo meetup el día jueves 27 de junio a las 6:30 pm. Quisieramos saber si tienes tiempo de asistir para así contar tu proyecto y que la comunidad se entere de esta iniciativa que tienes !

Quedo atenta 💕 Feliz inicio de semana !

**Comment by D4v1d98Ru1z** [comment]
¡Hola @teffcode, Muchas gracias por la invitación! 

Me encantaría dar a conocer el proyecto a la comunidad, pero hay un pequeño problema. Estoy ubicado en la ciudad de Bogotá en este momento y no tengo facilidad de viajar hasta Medellín para asistir al meetup. :cry: 

¡Que estes teniendo una excelente semana tú igual! :blush:
