### ISSUE TITLE
Tipografía y CSS

### ISSUE THREAD

**Issue by xaca** [MedellinCSS/meetup#12]
# Ahora, ¿Qué te gustaría?...

* [x] 🍄 Ser el próximo speaker
* [ ] 🌸 Dar feedback
* [ ] 🌻 Dar una idea
* [ ] 🚀 Otro

## Descripción
Hola mi nombre es Andrés Bedoya Tobón, podría hablar sobre tipografía y recomendaciones de uso en CSS, como bonus track puedo hablar sobre animate.css o normalize.css.

**Comment by xaca** [comment]
:thinking:

**Comment by teffcode** [comment]
Hola @xaca ! 

Está súper cool este tema 😃Te animarías a dar taller ?

**Comment by xaca** [comment]
Si, un taller claro 📚🆒

Descarga Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: Estefany Aguilar <notifications@github.com>
Enviado: Sunday, April 28, 2019 11:44:40 PM
Para: medellincss/meetup
Cc: Xaca Rana; Mention
Asunto: Re: [medellincss/meetup] Tipografía y CSS (#12)


Hola @xaca<https://github.com/xaca> !

Está súper cool este tema 😃Te animarías a dar taller ?

**Comment by teffcode** [comment]
Súper ! Posiblemente sea para el mes de julio pero te confirmamos bien en este mes de mayo, te parece ? ☺️

**Comment by xaca** [comment]
Listo, muchas gracias. Quedo pendiente. 🤘

Descarga Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: Estefany Aguilar <notifications@github.com>
Enviado: Sunday, April 28, 2019 11:54:18 PM
Para: medellincss/meetup
Cc: Xaca Rana; Mention
Asunto: Re: [medellincss/meetup] Tipografía y CSS (#12)


Súper ! Posiblemente sea para el mes de julio pero te confirmamos bien en este mes de mayo, te parece ? ☺️
