### ISSUE TITLE
Speaker

### ISSUE THREAD

**Issue by vanessamarely** [MedellinCSS/meetup#2]
# Ahora, ¿Qué te gustaría?...

* [x] 🍄 Ser el próximo speaker
* [ ] 🌸 Dar feedback
* [ ] 🌻 Dar una idea
* [ ] 🚀 Otro

## Descripción
Mi propuesta de charla: SVG & CSS 

En la actualidad, las páginas Web son mucho más dinámicas, orientadas a mostrar una buena experiencia de usuario, sin perder entre los principios clásicos del diseño que se vea bonita y que sea funcional; para no afectar su rendimiento, se busca que en ellas se puedan implementar imágenes escalables, que mantengan su calidad  y es así que surge el SVG (Scalable Vector Graphics), el cual es un formato vectorial de gráficos bidimensionales, que reúne las características mencionadas y que puede ser estilizado y animado a través del CSS (por sus siglas Cascade Style Sheet o hojas de estilo en cascada). 

En esta charla aprenderás que es SVG, cómo se pueden crear formas simples, que herramientas se pueden usar para crear gráficos avanzados y cómo estilizar y animar estos gráficos escalables haciendo uso del CSS.

https://slides.com/vanessamarely/svg-css#/

**Comment by teffcode** [comment]
Excelente @vanessamarely 💜 escogiste un tema increíble 😍 Nos encantan tus slides !!!

Graciasss por querer ser parte de nuestro grupo de speakers 🎤🎨

Te gustaría dar esta charla el *30 de agosto* ?

**Comment by vanessamarely** [comment]
Hola, como estas?

Muchas gracias por tener en cuenta mi tema 😊.  La fecha esta perfecta para
mi👌.

La charla la di hace poco en Pioneras, pero no se si quieren que en vez de
ser enfocada mas a SVG, se mencione mas del CSS?, me avisan si les parece
bien, para hacer otros slides 😋

Saludos,
