### ISSUE TITLE
Browser Rendering / Hardware Accelerated CSS

### ISSUE THREAD

**Issue by jmtov** [MedellinCSS/meetup#3]
# Ahora, ¿Qué te gustaría?...

* [x] 🍄 Ser el próximo speaker
* [ ] 🌸 Dar feedback
* [ ] 🌻 Dar una idea
* [ ] 🚀 Otro

## Descripción

Composite Layers y aceleración por hardware para CSS.

Me gustaría poder hablar sobre la manera en que los exploradores empiezan a pintar todo el esquema de una página web para así dar solución a preguntas como:
- ¿De qué depende que las animaciones y transiciones de algunos elementos sea más fluidos en uno u otro explorador?
- ¿Cómo puedo hacer la depuración de las animaciones y transiciones para identificar qué puede estar causando renderizaciones innecesarias?
- ¿Cómo hacer para que las animaciones sean mucho más fluidas en dispositivos móviles?
- ¿Cuáles son las buenas prácticas para tratar con transiciones en los elementos de un sitio web?

**Comment by teffcode** [comment]
Excelente @jmtov 💛 un súper tema 🎉 

Graciasss por querer ser parte de nuestro grupo de speakers 🎤🎨

Te gustaría dar esta charla el *26 de julio* ?

**Comment by jmtov** [comment]
¡Hola, @teffcode!

Sí, me gustaría. ¿Qué debo hacer?

**Comment by teffcode** [comment]
@jmtov podrías regalarme tu correo ? Acabo de agregarte a Twitter para que conversemos ! Me cuentas, quedo pendiente 🤗

**Comment by jmtov** [comment]
¡Hola, Estefany!

Mi correo es. jmtov4@gmail.com <mailto:jmtov4@gmail.com>

¡Saludos! 😺


Enrique Mejía
+57 (301) 708-4384
jmtov4@gmail.com
