### ISSUE TITLE
speaker

### ISSUE THREAD

**Issue by HugoLaguna** [MedellinCSS/meetup#4]
# Ahora, ¿Qué te gustaría?...

* [x] 🍄 Ser el próximo speaker
* [ ] 🌸 Dar feedback
* [ ] 🌻 Dar una idea
* [ ] 🚀 Otro

## Descripción

Hola mi nombre es Hugo Laguna, soy desarrollador front-end desde hace 10 años, también soy diseñador gráfico y  encargado de marketing en mi actual empresa. 

Deseo dar una charla sobre ' Transitions, Animation & Transfrom ' . Con una duración aproximada de 40 - 50 minutos. Los objetivos son definir las diferencias entre Animaciones y Transiciones, aprender a optimizarlas a través de CSS y conocer la propiedad de 'transform'.

### Temas
* Introducción al CSS como motor de animaciones
* Diferencias entre Animación y Transición
* [Javascript] Asignación de clases con  'classList'
* Cubic-Bezier
* Transicion (  delay,  duration, property, timing-function )
* @keyframe
* Animation ( direction, fill-mode , iteration, play-state, )
* transform  ( rotate, translate, scale, matrix3d, skew )

**Comment by luisafvaca** [comment]
@HugoLaguna Muchas gracias por querer ser parte de nuestra comunidad, nos encanta tu propuesta, crees poder tener disponibilidad para el 30 de Agosto ?

**Comment by HugoLaguna** [comment]
Si me viene bien, pero vi que otra persona esta proponiendo una charla parecida en el issue #1 , para el mismo día.  como se haría ?

**Comment by HugoLaguna** [comment]
https://github.com/HugoLaguna/animations-transitions-css
