### ISSUE TITLE
Stacking context y CSS variables

### ISSUE THREAD

**Issue by henryzarza** [MedellinCSS/meetup#5]
# Ahora, ¿Qué te gustaría?...

* [x] 🍄 Ser el próximo speaker
* [ ] 🌸 Dar feedback
* [ ] 🌻 Dar una idea
* [ ] 🚀 Otro

## Descripción
Hola! me llamo Henry, soy desarrollador frontend hace aproximadamente 3 años, me gustaría dar una charla sobre `Stacking context y CSS variables`

El stacking context es una conceptualización tridimensional de HTML para entender como los elementos son colocados o renderizados por los navegadores. Uno de los features más interesantes de CSS son las variables, en esta charla se abarcarán conceptos fundamentales e interesantes sobre estas.

**Comment by teffcode** [comment]
Hola @henryzarza  !!!

Súper, qué buen tema... tienes disponibilidad para el mes de marzo (finales) ?

**Comment by henryzarza** [comment]
Hola @teffcode la charla la podría dar para después del 15 de agosto
