### ISSUE TITLE
Modular CSS naming conventions - OOCSS and BEM (Speaker)

### ISSUE THREAD

**Issue by camigomezdev** [MedellinCSS/meetup#6]
# Ahora, ¿Qué te gustaría?...

* [X] 🍄 Ser el próximo speaker
* [ ] 🌸 Dar feedback
* [ ] 🌻 Dar una idea
* [ ] 🚀 Otro

## Descripción

Hello, soy Maria Camila Gómez y trabajo como Web Engineer en Huge. 
En mi proceso de aprendizaje y desarrollo web me he dado cuenta de la importancia de mantener un codigo limpio, entendible y mantenible para uno y para las personas que trabajan en un proyecto. Por ello quiero compartir un pequeña charla de como mejorar tus practicas en el CSS de tu aplicación, y seguramente facilitarte la vida mas adelante.

**Comment by teffcode** [comment]
Hola @camigomez35 !!! 

Nos encanta el tema... tienes disponibilidad para el mes de marzo (finales) ?

**Comment by camigomezdev** [comment]
Hola, claro, solo es que me confirmen que dia sería para revisar si tengo disponibilidad. :)
