### ISSUE TITLE
The 12 principles of UX in motion with pure CSS .... and a little of js

### ISSUE THREAD

**Issue by zucerkia** [MedellinCSS/meetup#9]
# Ahora, ¿Qué te gustaría?...

* [x] 🍄 Ser el próximo speaker
* [ ] 🌸 Dar feedback
* [ ] 🌻 Dar una idea
* [ ] 🚀 Otro

## Descripción
Hola!! me gustaría hablar de cuales son las propiedades clave de CSS para lograr animaciones geniales con los 12 principios de UX en el movimiento y mostrar ejemplos de cada uno de estos. Es la primera vez que me atrevo a hacer una charla y agradezco de antemano cualquier ayuda ( o apoyo emocional XD ) que me brinden, en especial sobre como debería estructurar la charla para que no sea aburridora, tips, consejos etc.

muchas gracias por inspirarme y animarme a aprender enseñando 😄

**Comment by teffcode** [comment]
Hola @zucerkia ! 

Me gusta mucho el tema y me alegra mucho que quieras incursionar como speaker 😃 Por supuesto, tendrás toda nuestra asesoría.

Por otro lado, esta charla quedaría para agosto aproximadamente pero te estaríamos confirmando. Te parece ? ☺️

**Comment by zucerkia** [comment]
si!! me parece bien, así tengo tiempo para ir preparando los slides y todo.

**Comment by teffcode** [comment]
Hola @zucerkia 😃 tienes disponibilidad en julio ? si sí, ¿Podrías enviarme un mensaje a Twitter o Instagram con tu número de celular porfa? Es para agregarte a un grupo en WhatsApp y contarte lo que haremos !

Me encuentras como @teffcode en Instagram y en Twitter. 

Feliz inicio de semana 💕
